### PR TITLE
Reorganise ui dir structure

### PR DESCRIPTION
**Pull request by mitjade**
Proposed reorganisation:

`ui -> post -> components`
`ui -> post -> containers`
`ui -> post -> graphql`
`ui -> post -> reducers`

`ui -> counter -> containers`
`ui -> counter -> graphql`
`ui -> counter -> reducers`

Deleted `store -> reducers`

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko Your thoughts on this.

Should we leave `ui -> components`, or move it in to something like `core` or `main`

**Comment by vlasenko** [comment]
@mitjade I would prefer deeper decoupling with moving out UI and server-side code for the single feature into feature-specific dir, but shallow decoupling is okay too for the start. Maybe leave `ui ->  components` and `ui -> styles`  so that users understand they can write code there. Generally we should have some placeholder files for the users to quickly understand where they can start write their code. In addition to our examples.

**Comment by vlasenko** [comment]
@mitjade But any way to decouple examples is fine. Let it be multi-step process. Let's start from decoupling approaches that can be implemented easily and then improve on that

**Comment by mitjade** [comment]
@vlasenko So also extract schema and resolvers to separate files and into it's own dir?

For something like `server -> api -> middleware -> graphql.js` this might a bit more tricky.

**Comment by mitjade** [comment]
@vlasenko Would this be than good enough to merge, or should we continue in this branch until we have complete decoupling.

**Comment by vlasenko** [comment]
@mitjade Yes. I think examples should be fully decoupled ideally, including separation of schema and resolvers. Yes, it might be tricky to achieve this, but this is something to consider. If it's too difficult then let's do what we can and postpone hard things for now.

**Comment by vlasenko** [comment]
@mitjade It's good enough to merge

**Comment by mitjade** [comment]
Will try to extract schema and resolvers into separate files, since this might come in handy when you want to remove the examples, or as an example how this can be achieved.

Will attempt complete decoupling sometime later.

**Comment by vlasenko** [comment]
@mitjade Yep, sure! Thanks!

**Comment by mitjade** [comment]
@vlasenko Just give me the thumbs up if you agree with my proposal for schema and resolvers separation for post example.

**Comment by mitjade** [comment]
I left count in the main schema and resolvers, so if anyone does not need to separate everything, we have both examples shown.

**Comment by vlasenko** [comment]
Looks very good! I think it's good to merge this work, thanks!

**Pull request merged**
