### PR TITLE
CRUD for posts and comments

### PR DESCRIPTION
**Pull request by mitjade**
This is a my take on how CRUD operations could be implemented for the post/comments example.

Still some improvements to be made, but should have the basic functionally of add, edit, delete with optimistic updates and no unnecessary round trips to refetch data.

Used `updateQueries` to update client side store. Did try also [Apollo Client’s new imperative store API](https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3#.ejr6np8ku), but was not able to make it work. 

Will fist try to improve the code a bit more (would love to get some feedback on what could be done better).

Then I also plan to implement subscriptions on this example.

### CODE REVIEW

**Comment by vlasenko** [comment]
Mitja, looks nice to me! 

One more thing in addition to those you have mentioned already is to consider using https://github.com/erikras/redux-form instead of `setState`. I think `redux-form` is de-facto standard for forms input for `redux`-based applications.

**Comment by mitjade** [comment]
Agreed. Will try to incorporate that as well.

**Comment by mitjade** [comment]
if I add `formReducer` to any react component, when I move to a different page (via react router), I keep getting:
 `Warning: setState(...): Cannot update during an existing state transition (such as within render or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to componentWillMount`

Added an example, if you try to add a new post. Just click `Add` and then `back`. Form works otherwise.

**Comment by vlasenko** [comment]
@mitjade I'm not quite sure what is causing this problem, but what I see is you are not quite correct about composition of High Order Components. E.g. it should not be like `withApollo(compose(reduxForm, ...))`. Instead it should be `compose(withApollo, reduxForm)`. I'm not sure if this helps with current issue, but `compose` should be at the top level for sure and shouldn't be wrapped by anything else.

**Comment by vlasenko** [comment]
@mitjade Also, why you do setState in the `redux-form` component?

**Comment by vlasenko** [comment]
Okay, let me look....

**Comment by mitjade** [comment]
Added a functional test component. If I navigate to it without wrapping it in `reduxForm`, I do not get the warning, otherwise, always.

**Comment by vlasenko** [comment]
@mitjade Yeah, looks like some problem in redux-form. Maybe it's not fully supporting React Router v4 yet?

**Comment by mitjade** [comment]
Seems to be a `react-router 4` issue, I checked out this starter kit, with `react-router 3` and there it works.

**Comment by mitjade** [comment]
Strange that I found no issue for this?

**Comment by vlasenko** [comment]
@mitjade Yes, but we are on the edge. Hence we can be first to see some issues :)

**Comment by mitjade** [comment]
Will leave `redux-form` out for now?

**Comment by vlasenko** [comment]
@mitjade Yes, lets leave it out for now

**Comment by mitjade** [comment]
ok

**Comment by mitjade** [comment]
Found [this](https://github.com/ReactTraining/react-router/issues/4713). Maybe updating to `react-router-redux` 5.0.0-alpha.4 could help? I see we use a special [repo](https://github.com/sysgears/react-router-redux).

**Comment by vlasenko** [comment]
@mitjade Yes, we are using slightly fixed alpha.3, it had severe packaging bug. But the fix should be included to alpha.4. So you can try to upgrade to alpha.4 and kill two birds with one stone hopefully :)

**Comment by mitjade** [comment]
Seems to work!

**Comment by vlasenko** [comment]
Awesome!

**Comment by mitjade** [comment]
Will finish refactoring tomorrow.

**Comment by vlasenko** [comment]
Yup. Sounds great! Have a good night!

**Comment by mitjade** [comment]
I would like to change the structure, so post example would be in it's own directory under `ui` dir.

something like:
`ui -> post -> components`
`ui -> post -> containers`
`ui -> post -> graphql`
`ui -> post -> reducers`

What should happen with the remaining:
`ui -> components`
`ui -> containers`
`ui -> graphql`
`ui -> style`

Keep them as is and add:
`ui -> post -> ...`
or have something like `core` or `main` beside `post`?

I would also move `store -> reducers` to `ui -> reducers`.

**Comment by vlasenko** [comment]
@mitjade Yes, I have thought about it. It would be nice to separate out different examples into different dirs, but lets do this in separate Pull Request

**Comment by mitjade** [comment]
ok, will finish this one today and then we can go from there

**Comment by mitjade** [comment]
Can you take a look if this would be good enough now, or suggest what could still be improved.

**Comment by vlasenko** [comment]
@mitjade Generally, its very good. But subscriptions still not implemented I think. Do you want to implement them in the separate Pull Request?

**Comment by mitjade** [comment]
Yes, I would like to do that separately. Found a bug if you add posts and then, click `Load more`. Will try to fix this.

**Comment by mitjade** [comment]
Would also like change the file structure before I go on to subscriptions. Will make a PR for that when this is merged.

**Comment by vlasenko** [comment]
Okay, it's fine with me. Let me know when you fix found bug and I will merge this PR.

**Comment by vlasenko** [comment]
@mitjade Since you are major contributor I would like that you have write permissions to this repository. So you can do merges yourself whenever you feel changes are ready. Still I would like that the work were done the same way. E.g. all major features should be developed in Pull Requests first or separate branches of this repo and then Pull Requests created from those branches and then when they changes are ready they will be merged with "Squash and merge" option.

**Comment by mitjade** [comment]
I'm honoured and thank you!

I agree that all mayor changes go through Pull Requests.

**Comment by vlasenko** [comment]
Awesome! Thank you for the hard work, Mitja! I highly appreciate your efforts!

**Comment by mitjade** [comment]
Had to reverse the post list order to make adding new posts work with cursor pagination.
Fixed a bug if you wanted to edit and then delete a comment.

Will add validation for inputs and then I think that is it.

**Comment by vlasenko** [comment]
Sounds good, thanks!

**Comment by mitjade** [comment]
It turns out that adding objects as `id: null` is not a good idea, for optimistic updates. `id: -1` seems to work better.

**Comment by mitjade** [comment]
OK. This should be it. 

So now I `Merge pull request` => `Squash and merge`?

**Comment by vlasenko** [comment]
@mitjade Yep!

**Pull request merged**
