### PR TITLE
add support for persistgraphql, optional, default not enabled

### PR DESCRIPTION
**Pull request by mitjade**
initial `extracted_queries.json` needs to exist even if `persistedQueries` -> false

### CODE REVIEW

**Comment by vlasenko** [comment]
Thank you!

**Comment by vlasenko** [comment]
Actually the implementation of this feature is bad. I'm against extra step needed during build that cannot be integrated with hot reloading and against static dependency on `extracted_queries.json`. After more closely examining this feature I would like to revert it for now

**Comment by mitjade** [comment]
Ok. Have any sugestions on how to automate this?

**Comment by vlasenko** [comment]
@mitjade There should be integration developed of `persistgraphql` with `webpack`, so that on any source file change the `extracted_queries.json` should be updated.

**Comment by vlasenko** [comment]
@mitjade I think webpack loader should be written for this task, the relevant webpack doc:
Webpack v1:
https://webpack.github.io/docs/how-to-write-a-loader.html

Webpack v2:
https://webpack.js.org/development/how-to-write-a-loader/

**Comment by mitjade** [comment]
Will look into this and try to implement this over the weekend.

**Comment by vlasenko** [comment]
@mitjade Please note, that I'm going to implement persistgraphql webpack loader soon, as well.

**Comment by mitjade** [comment]
OK, then I rather see you do it, since I am not that familiar with how to implement this.

What I've done is good enough for what I needed now and can wait till whenever you manage to do this.

**Comment by vlasenko** [comment]
Yes, thanks, once webpack loader will be ready for persistgraphql I will revist this Pull Request and try to merge it

**Pull request merged**
